name: Install pnpm
description: Install pnpm, Node.js and project dependencies

runs:
  using: 'composite'
  steps:
    - name: 🥸 Install pnpm
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      id: pnpm-install
      with:
        version: 11.4.0
        run_install: false

    - name: 🤞 Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: 24

    - name: ⚙️Install dependencies
      run: pnpm install
      shell: bash
