projects:
  SubQuery Governance:
    schema: https://subquery-governance-polkadot-prod.novasama-tech.org
    include:
      - src/renderer/shared/api/governance/**

  SubQuery Proxy:
    schema: https://subquery-proxy-polkadot-stg.novasama-tech.org
    include:
      - src/renderer/entities/multisig-accounts/**
      - src/renderer/entities/proxy/**

  SubQuery Multi Chain Account Management:
    schema: https://subquery-accounts-prod.novasama-tech.org
    include:
      - src/renderer/domains/network/multisig-operation/**
      - src/renderer/domains/network/account-sync/**

  SubQuery History:
    schema: https://subquery-history-polkadot-prod.novasama-tech.org
    include:
      - src/renderer/entities/staking/**

  SubQuery Collectives:
    schema: https://subquery-collectives-stg.novasama-tech.org
    include:
      - src/renderer/domains/collectives/**
