name: Setup s3cmd
description: That action will setup s3cmd
inputs:
  s3_access_key:
    description: 'Access key to s3'
    required: true
  s3_secret_key:
    description: 'Secret key for s3'
    required: true
  s3_region:
    description: 'Region for s3'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up S3cmd cli tool
      uses: s3-actions/s3cmd@v1.6.1
      with:
        provider: scaleway
        region: ${{ inputs.s3_region }}
        secret_key: ${{ inputs.s3_secret_key }}
        access_key: ${{ inputs.s3_access_key }}
