export const TEST_IDS = {
  ONBOARDING: {
    VAULT_BUTTON: 'onboarding-vault-button',
    WATCH_ONLY_BUTTON: 'onboarding-watch-only-button',
    NOVA_WALLET_BUTTON: 'onboarding-nova-wallet-button',
    WALLET_CONNECT_BUTTON: 'onboarding-wallet-connect-button',
    LEDGER_BUTTON: 'onboarding-ledger-button',
    POLKADOT_EXTENSION_BUTTON: 'onboarding-polkadot-extension-button',
    TALISMAN_BUTTON: 'onboarding-talisman-extension-button',
    SUBWALLET_BUTTON: 'onboarding-subwallet-extension-button',
    EXISTING_WALLET_ALERT: 'onboarding-existing-wallet-alert',
    WALLET_NAME_INPUT: 'onboarding-wallet-name-input',
    WALLET_ADDRESS_INPUT: 'onboarding-wallet-address-input',
    IMPORT_DATABASE_BUTTON: 'onboarding-import-database-button',
  },
  ASSETS: {
    SETTINGS_WIDGET: 'assets-settings-widget',
    PAGE_VIEW: 'page-view',
    SEND_ARROW_ICON: 'Icon:sendArrow',
    RECEIVE_ARROW_ICON: 'Icon:receiveArrow',
    SHELF_RIGHT_ARROW_ICON: 'Icon:shelfRight',
    ASSET_DETAILS: 'assets-asset-details',
    PORTFOLIO_LIST: 'assets-portfolio-list',
    TOKEN_PLATE: 'assets-token-plate',
  },
  COMMON: {
    WALLET_BUTTON: 'common-wallet-button',
    BACK_BUTTON: 'common-back-button',
    CONTINUE_BUTTON: 'common-continue-button',
    INFO_BUTTON: 'common-info-button',
    APPLY_BUTTON: 'common-apply-button',
  },
  WALLET_MANAGEMENT: {
    WALLET_SEARCH: 'wallet-search-input',
    WALLET_ITEM: 'wallet_item',
    DROPDOWN_ITEM_VIEW_DETAILS: 'view_wallet_details',
    DROPDOWN_ITEM_DELEGATE: 'delegate-proxy',
    DROPDOWN_ACTIONS: 'wallet-actions',
  },
  OPERATIONS: {
    CONFIRM_NETWORK_FEE: 'operations-confirm-network-fee',
    ESTIMATE_FEE: 'operations-estimate-fee',
    AMOUNT_INPUT: 'operations-amount-input',
    AVAILABLE_BALANCE: 'available-balance',
    AVAILABLE_BALANCE_LOADER: 'available-balance-loader',
    RECIPIENT_INPUT: 'operations-recipient-input',
    RECIPIENT_CARD: 'operations-recipient-card',
    RECIPIENT_CLEAR: 'operations-recipient-clear',
    QR_CODE_CONTAINER: 'operations-qr-code-container',
    SIGNATORY_SELECTOR: 'operations-signatory-selector',
    SIGNATORY_SELECTOR_OPTION: 'Address',
    XCM_SELECTOR: 'operations-xcm-selector',
    MYSELF_BUTTON: 'myself-button',
    FEE_LOADER: 'fee-loader',
  },
  GOVERNANCE: {
    FILTER_BUTTON: 'governance-filter-button',
    FILTER_VOTED_OPTION: 'governance-filter-voted-option',
    FILTER_NOT_VOTED_OPTION: 'governance-filter-not-voted-option',
    SEARCH_INPUT: 'governance-search-input',
    PROPOSAL_ITEM: 'governance-proposal-item',
    PROPOSAL_ID: 'governance-proposal-id',
    PROPOSAL_VOTE_DETAILS: 'governance-proposal-vote-details',
  },
  MULTISIG: {
    SIGNATORY_COMBOBOX: 'multisig-signatory-combobox',
    SIGNATORY_NAME: 'multisig-signatory-name',
    FLEXIBLE_MULTISIG: 'flexible-multisig',
    REGULAR_MULTISIG: 'regular-multisig',
    NETWORK_EDIT_BUTTON: 'network-edit-buton',
    FEE_MODAL: 'multisig-fee-modal',
    MULTISIG_WALLET_NAME: 'multisig-wallet-name',
    SIGNER_SELECTOR: 'multisig-signer-selector',
    THRESHOLD_SELECTOR: 'multisig-threshold-selector',
    THRESHOLD_OPTION: 'multisig-threshold-option',
    NETWORK_OPTION: 'multisig-network-option',
    CREATE_PURE_BUTTON: 'create-pure-button',
    ASSIGN_CONTROL_BUTTON: 'assign-control-button',
  },
  TRANSFER: {
    MODAL: 'transfer-modal',
  },
  DASHBOARD: {
    HOLDING_ROW: 'dashboard-holding-row',
    BALANCE_TYPE_CHIP: 'dashboard-balance-type-chip',
  },
  PROXY_FORM: {
    ADDRESS_INPUT: 'proxy-address-input',
  },
  ADD_BUTTON: 'button-add',
  CLOSE_BUTTON: 'Icon:close',
  VALIDATIONS: {
    PERMISSION: 'permission-error',
    MISSING_ACCOUNT: 'missing-account-error',
    BALANCE: 'balance-error',
    FATAL: 'fatal-error',
    RULE: 'rule-error',
    INACTIVE_ACCOUNT: 'inactive-account-error',
  },
} as const;
