export const TEST_IDS = {
  ONBOARDING: {
    VAULT_BUTTON: 'onboarding-vault-button',
    WATCH_ONLY_BUTTON: 'onboarding-watch-only-button',
    NOVA_WALLET_BUTTON: 'onboarding-nova-wallet-button',
    WALLET_CONNECT_BUTTON: 'onboarding-wallet-connect-button',
    LEDGER_BUTTON: 'onboarding-ledger-button',
    POLKADOT_EXTENSION_BUTTON: 'onboarding-polkadot-extension-button',
    TALISMAN_BUTTON: 'onboarding-talisman-extension-button',
    SUBWALLET_BUTTON: 'onboarding-subwallet-extension-button',
    WALLET_NAME_INPUT: 'onboarding-wallet-name-input',
    WALLET_ADDRESS_INPUT: 'onboarding-wallet-address-input',
    IMPORT_DATABASE_BUTTON: 'onboarding-import-database-button',
  },
  ASSETS: {
    SETTINGS_WIDGET: 'assets-settings-widget',
    SEND_ARROW_ICON: 'Icon:sendArrow',
    RECEIVE_ARROW_ICON: 'Icon:receiveArrow',
    SHELF_RIGHT_ARROW_ICON: 'Icon:shelfRight',
    ASSET_DETAILS: 'assets-asset-details',
    PORTFOLIO_LIST: 'assets-portfolio-list',
    TOKEN_PLATE: 'assets-token-plate',
  },
  COMMON: {
    WALLET_BUTTON: 'common-wallet-button',
    BACK_BUTTON: 'common-back-button',
    CONTINUE_BUTTON: 'common-continue-button',
    INFO_BUTTON: 'common-info-button',
  },
  OPERATIONS: {
    CONFIRM_NETWORK_FEE: 'operations-confirm-network-fee',
    ESTIMATE_FEE: 'operations-estimate-fee',
    AMOUNT_INPUT: 'operations-amount-input',
    RECIPIENT_INPUT: 'operations-recipient-input',
    QR_CODE_CONTAINER: 'operations-qr-code-container',
    SIGNATORY_SELECTOR: 'operations-signatory-selector',
    SIGNATORY_SELECTOR_OPTION: 'Address',
    XCM_SELECTOR: 'operations-xcm-selector',
  },
  GOVERNANCE: {
    FILTER_BUTTON: 'governance-filter-button',
    FILTER_VOTED_OPTION: 'governance-filter-voted-option',
    FILTER_NOT_VOTED_OPTION: 'governance-filter-not-voted-option',
    SEARCH_INPUT: 'governance-search-input',
    PROPOSAL_ITEM: 'governance-proposal-item',
    PROPOSAL_ID: 'governance-proposal-id',
    PROPOSAL_VOTE_DETAILS: 'governance-proposal-vote-details',
  },
  MULTISIG: {
    SIGNATORY_COMBOBOX: 'multisig-signatory-combobox',
  },
  TRANSFER: {
    MODAL: 'transfer-modal',
  },
  CLOSE_BUTTON: 'Icon:close',
} as const;
