runs:
  using: 'composite'
  steps:
    - name: Run tests
      run: |
        python - <<END
        import re
        import subprocess as sp
        import sys
        import threading
        import time
        done = False
        def update():
          # prevent CI from killing the process for inactivity
          while not done:
            time.sleep(5)
            print ("Running...")
        t = threading.Thread(target=update)
        t.dameon = True
        t.start()
        def run():
          p = sp.Popen('pnpm test:integration',
                      shell=True, stdout=sp.PIPE, stderr=sp.PIPE, stdin=sp.PIPE)
          return p.communicate()
        success = re.compile(r'PASS')
        stdout, stderr = run()
        done = True
        print (stderr.decode())
        print (stdout.decode())
        if success.search(stderr.decode() + stdout.decode()):
          sys.exit(0)
        else:
          sys.exit(1) # make sure we fail if the tests fail

        END
        EXIT_CODE=$?
      shell: bash
