name: Upload to s3
description: That action will setup s3cmd
inputs:
  s3_access_key:
    description: 'Access key to s3'
    required: true
  s3_secret_key:
    description: 'Secret key for s3'
    required: true
  s3_region:
    description: 'Region for s3'
    required: true
  s3_bucket:
    description: 'Bucket name'
    required: true
  source:
    description: 'Directory or file to upload'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up s3cmd cli tool
      uses: ./.github/workflows/setup-s3cmd
      with:
        s3_region: ${{ inputs.s3_region }}
        s3_secret_key: ${{ inputs.s3_secret_key }}
        s3_access_key: ${{ inputs.s3_access_key }}

    - name: List available S3 buckets
      run: s3cmd ls
      shell: bash
    
    - name: Clean bucket
      run: |
        s3cmd rm --recursive --force "${{ env.S3_BUCKET }}/*"
      shell: bash

    - name: Deploy to bucket
      id: deploy_to_bucket
      run: |
        base_directory="${{ inputs.source }}"
        destination_s3="${{ env.S3_BUCKET }}"
        
        # Function to get mime type based on file extension
        get_mime_type() {
          case "$1" in
            *.html) echo "text/html";;
            *.css) echo "text/css";;
            *.js) echo "application/javascript";;
            *.mjs) echo "application/javascript";;
            *.json) echo "application/json";;
            *.png) echo "image/png";;
            *.jpg|*.jpeg) echo "image/jpeg";;
            *.svg) echo "image/svg+xml";;
            *.woff2) echo "font/woff2";;
            *) echo "text/plain";;
          esac
        }
        
        # Upload files with appropriate mime types
        find "$base_directory" -type f | while read -r file; do
          relative_path="${file#$base_directory/}"
          mime_type=$(get_mime_type "$file")
          s3cmd sync "$file" "${destination_s3}/${relative_path}" --acl-public --mime-type="$mime_type"
        done
      shell: bash

