ARG BUN_IMAGE_VERSION=1.1-slim
ARG BUILD_TYPE=production

FROM oven/bun:${BUN_IMAGE_VERSION} AS build
ARG BUILD_TYPE
WORKDIR /project

COPY . .
RUN bun install --frozen-lockfile

RUN if [ "$BUILD_TYPE" = "development" ]; then \
        bun run build:staging && bun run postbuild:staging; \
    else\
        bun run build && bun run postbuild; \
    fi

FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html
COPY --from=build /project/release/build .

RUN rm /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
