ARG NODE_JS_IMAGE_VERSION=20-alpine
ARG BUILD_TYPE=production

FROM node:${NODE_JS_IMAGE_VERSION} AS build

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && \
    corepack prepare pnpm@9

WORKDIR /project

COPY package.json pnpm-lock.yaml ./
COPY .papi ./.papi/

RUN pnpm install --frozen-lockfile

RUN if [ "$BUILD_TYPE" = "development" ]; then \
        pnpm build:staging && pnpm postbuild:staging; \
    else\
        pnpm build && pnpm postbuild; \
    fi

COPY . .

FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html

COPY --from=build /project/release/build .

RUN rm /etc/nginx/conf.d/default.conf

COPY docker/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
