FROM mcr.microsoft.com/playwright:v1.38.0-jammy

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && \
    corepack prepare pnpm@10 --activate

WORKDIR /tests

COPY package.json pnpm-lock.yaml ./
COPY .papi ./.papi/

RUN pnpm install --frozen-lockfile

COPY . .

CMD [ "pnpm", "test:system" ]
