FROM mcr.microsoft.com/playwright:v1.58.0-noble

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && \
    corepack prepare pnpm@11.4.0 --activate

WORKDIR /tests

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY .papi ./.papi/

RUN pnpm install --frozen-lockfile

COPY . .

CMD [ "pnpm", "test:system" ]
