ARG NODE_JS_IMAGE_VERSION=20-alpine

FROM node:${NODE_JS_IMAGE_VERSION} AS build

ADD . /project
WORKDIR /project
RUN npm install -g pnpm
RUN pnpm build
RUN pnpm postbuild

FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html

COPY --from=build /project/release/build .

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

# Запускаем Nginx в фореанде
CMD ["nginx", "-g", "daemon off;"]