import {
  accountIdSchema,
  addressSchema,
  boolSchema,
  bytesHexSchema,
  bytesSchema,
  i64Schema,
  nullSchema,
  perbillSchema,
  permillSchema,
  storageKeySchema,
  structHexSchema,
  textSchema,
  u128Schema,
  u16Schema,
  u32Schema,
  u64Schema,
  u8Schema,
} from './primitives';
import {
  complexSchema,
  enumTypeSchema,
  enumValueLooseSchema,
  enumValueSchema,
  objectSchema,
  optionalSchema,
  tuppleMapSchema,
  vecSchema,
} from './structs';

export const pjsSchema = {
  perbill: perbillSchema,
  permill: permillSchema,
  u8: u8Schema,
  u16: u16Schema,
  u32: u32Schema,
  i64: i64Schema,
  u64: u64Schema,
  u128: u128Schema,
  text: textSchema,
  null: nullSchema,
  bytes: bytesSchema,
  bytesHex: bytesHexSchema,
  accountId: accountIdSchema,
  address: addressSchema,
  storageKey: storageKeySchema,
  bool: boolSchema,
  blockHeight: u32Schema,
  structHex: structHexSchema,

  object: objectSchema,
  optional: optionalSchema,
  enumType: enumTypeSchema,
  enumValue: enumValueSchema,
  enumValueLoose: enumValueLooseSchema,
  tuppleMap: tuppleMapSchema,
  complex: complexSchema,
  vec: vecSchema,
};
