name: 'Run System Tests'
description: 'Executes Playwright system tests and sends notification to Telegram'

inputs:
  telegram_token:
    description: 'Telegram Bot Token'
    required: true
  telegram_to:
    description: 'Telegram Channel ID'
    required: true
  test_grep:
    description: 'Test grep pattern'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Playwright tests
      id: playwright_tests
      continue-on-error: true
      shell: bash
      run: |
        allurectl watch -- npx playwright test --grep ${{ inputs.test_grep }}

    - name: Get allure report url
      shell: bash
      run: |
        printenv | grep ALLURE_ 

    - name: Prepare commit info
      shell: bash
      run: |
        COMMIT_INFO="Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
        echo "COMMIT_INFO<<EOF" >> $GITHUB_ENV
        echo "$COMMIT_INFO" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    # - name: Notify Telegram channel
    #   uses: appleboy/telegram-action@master
    #   with:
    #     to: ${{ inputs.telegram_to }}
    #     token: ${{ inputs.telegram_token }}
    #     format: markdown
    #     message: |
    #       📋 Playwright Test Report Published
    #       URL: ${{ env.REPORT_URL }}
    #       ${{ env.TEST_SUMMARY }}
    #       ${{ env.COMMIT_INFO }}
