import { type RegistryTypes } from '@polkadot/types/types';

export const types: RegistryTypes = {
  Address: 'AccountId',
  Amount: 'i128',
  AmountOf: 'Amount',
  AssetDetails: {
    name: 'Vec<u8>',
    asset_type: 'AssetType',
    existential_deposit: 'Balance',
    locked: 'bool',
  },
  AssetDetailsT: 'AssetDetails',
  AssetInstance: 'AssetInstanceV1',
  AssetMetadata: {
    symbol: 'Vec<u8>',
    decimals: 'u8',
  },
  AssetPair: {
    asset_in: 'AssetId',
    asset_out: 'AssetId',
  },
  AssetType: {
    _enum: {
      Token: 'Null',
      PoolShare: '(AssetId,AssetId)',
    },
  },
  BalanceInfo: {
    amount: 'Balance',
    assetId: 'AssetId',
  },
  BalanceOf: 'Balance',
  Chain: {
    genesisHash: 'Vec<u8>',
    lastBlockHash: 'Vec<u8>',
  },
  ClassData: {
    is_pool: 'bool',
  },
  ClassId: 'u64',
  ClassIdOf: 'ClassId',
  ClassInfo: {
    metadata: 'Vec<u8>',
    total_issuance: 'TokenId',
    owner: 'AccountId',
    data: 'ClassData',
  },
  ClassInfoOf: 'ClassInfo',
  Currency: 'AssetId',
  CurrencyId: 'AssetId',
  CurrencyIdOf: 'AssetId',
  Fee: { numerator: 'u32', denominator: 'u32' },
  Intention: {
    who: 'AccountId',
    asset_sell: 'AssetId',
    asset_buy: 'AssetId',
    amount: 'Balance',
    discount: 'bool',
    sell_or_buy: 'IntentionType',
  },
  IntentionId: 'Hash',
  IntentionType: {
    _enum: ['SELL', 'BUY'],
  },
  LBPWeight: 'u32',
  LookupSource: 'AccountId',
  MultiAsset: 'MultiAssetV1',
  MultiLocation: 'MultiLocationV1',
  OrderedSet: 'Vec<AssetId>',
  OrmlAccountData: {
    free: 'Balance',
    frozen: 'Balance',
    reserved: 'Balance',
  },
  Pool: {
    owner: 'AccountId',
    start: 'BlockNumber',
    end: 'BlockNumber',
    assets: 'AssetPair',
    initial_weights: 'LBPWeight',
    final_weights: 'LBPWeight',
    weight_curve: 'WeightCurveType',
    pausable: 'bool',
    paused: 'bool',
    fee: 'Fee',
    fee_receiver: 'AccountId',
  },
  PoolId: 'AccountId',
  Price: 'Balance',
  TokenData: {
    locked: 'bool',
  },
  TokenId: 'u64',
  TokenIdOf: 'TokenId',
  TokenInfo: {
    metadata: 'Vec<u8>',
    owner: 'AccountId',
    data: 'TokenData',
  },
  TokenInfoOf: 'TokenInfo',
  VestingSchedule: {
    start: 'BlockNumber',
    period: 'BlockNumber',
    period_count: 'u32',
    per_period: 'Compact<Balance>',
  },
  VestingScheduleOf: 'VestingSchedule',
  WeightCurveType: {
    _enum: ['Linear'],
  },
  Xcm: 'XcmV1',
  XcmOrder: 'XcmOrderV1',
};
