import {
  accountIdSchema,
  boolSchema,
  bytesSchema,
  i64Schema,
  perbillSchema,
  storageKeySchema,
  textSchema,
  u128Schema,
  u16Schema,
  u32Schema,
  u64Schema,
} from './primitives';
import {
  complexSchema,
  enumTypeSchema,
  enumValueLooseSchema,
  enumValueSchema,
  objectSchema,
  optionalSchema,
  tuppleMapSchema,
  vecSchema,
} from './structs';

export const pjsSchema = {
  perbill: perbillSchema,
  u16: u16Schema,
  u32: u32Schema,
  i64: i64Schema,
  u64: u64Schema,
  u128: u128Schema,
  text: textSchema,
  bytes: bytesSchema,
  accountId: accountIdSchema,
  storageKey: storageKeySchema,
  bool: boolSchema,

  object: objectSchema,
  optional: optionalSchema,
  enumType: enumTypeSchema,
  enumValue: enumValueSchema,
  enumValueLoose: enumValueLooseSchema,
  tuppleMap: tuppleMapSchema,
  complex: complexSchema,
  vec: vecSchema,
};
