import { attach, combine, createStore, sample } from 'effector';

import { type Wallet } from '@/shared/core';
import { accountService, accounts, identity } from '@/domains/network';
import { contactModel } from '@/entities/contact';
import { walletModel, walletUtils } from '@/entities/wallet';
import { walletSelectUI } from '@/features/wallet-select';

const $autoNamedWallets = combine(
  {
    wallets: walletModel.$allWallets,
    accounts: accounts.$list,
    contacts: contactModel.$contacts,
    identities: identity.$list,
  },
  ({ wallets, accounts, contacts, identities }) => {
    return wallets.filter((wallet) => {
      // Only wallet types the app names on the user's behalf. Everything else
      // got its name from the user at pairing time.
      if (!walletUtils.isAnyMultisig(wallet) && !walletUtils.isProxied(wallet)) return false;

      return accountService.isWalletNameAutoGenerated({ wallet, accounts, contacts, identities });
    });
  },
);

const $visibleAutoNamed = $autoNamedWallets.map((wallets) => wallets.filter((w) => !w.hiddenReason));
const $hiddenAutoNamed = $autoNamedWallets.map((wallets) => wallets.filter((w) => w.hiddenReason === 'unnamed'));

const $mode = combine($visibleAutoNamed, $hiddenAutoNamed, (visible, hidden): 'hide' | 'unhide' | 'none' => {
  if (visible.length > 0) return 'hide';
  if (hidden.length > 0) return 'unhide';
  return 'none';
});

const $optimisticMode = createStore<'hide' | 'unhide' | null>(null);
const $displayMode = combine($mode, $optimisticMode, (mode, optimisticMode) => optimisticMode ?? mode);

const hideAllFx = attach({
  source: $visibleAutoNamed,
  effect: async (wallets: Wallet[]) => {
    if (wallets.length === 0) return [];
    await walletModel.hideWallets(wallets);
    return wallets;
  },
});

const unhideAllFx = attach({
  source: $hiddenAutoNamed,
  effect: async (wallets: Wallet[]) => {
    if (wallets.length === 0) return [];
    await walletModel.restoreWallets(wallets);
    return wallets;
  },
});

$optimisticMode
  .on(hideAllFx, () => 'unhide' as const)
  .on(unhideAllFx, () => 'hide' as const)
  .reset([hideAllFx.finally, unhideAllFx.finally]);

sample({
  clock: [hideAllFx, unhideAllFx],
  fn: () => true,
  target: walletSelectUI.dropdownLoadingChanged,
});

sample({
  clock: [hideAllFx.finally, unhideAllFx.finally],
  fn: () => false,
  target: walletSelectUI.dropdownLoadingChanged,
});

export const hideUnnamedWalletsModel = {
  $mode,
  $displayMode,
  $isUpdating: combine(hideAllFx.pending, unhideAllFx.pending, (isHiding, isUnhiding) => isHiding || isUnhiding),
  $visibleAutoNamed,
  $hiddenAutoNamed,
  hideAll: hideAllFx,
  unhideAll: unhideAllFx,
};
