import { attach, combine } from 'effector';

import { type Wallet } from '@/shared/core';
import { accountService, accounts, identity } from '@/domains/network';
import { contactModel } from '@/entities/contact';
import { walletModel, walletUtils } from '@/entities/wallet';

const $autoNamedWallets = combine(
  {
    wallets: walletModel.$allWallets,
    accounts: accounts.$list,
    contacts: contactModel.$contacts,
    identities: identity.$list,
  },
  ({ wallets, accounts, contacts, identities }) => {
    return wallets.filter((wallet) => {
      const isTargetType = walletUtils.isAnyMultisig(wallet) || walletUtils.isProxied(wallet);
      if (!isTargetType) return false;

      return accountService.isWalletNameAutoGenerated({ wallet, accounts, contacts, identities });
    });
  },
);

const $visibleAutoNamed = $autoNamedWallets.map((wallets) => wallets.filter((w) => !w.isHidden));
const $hiddenAutoNamed = $autoNamedWallets.map((wallets) => wallets.filter((w) => Boolean(w.isHidden)));

const $mode = combine($visibleAutoNamed, $hiddenAutoNamed, (visible, hidden): 'hide' | 'unhide' | 'none' => {
  if (visible.length > 0) return 'hide';
  if (hidden.length > 0) return 'unhide';
  return 'none';
});

const hideAllFx = attach({
  source: $visibleAutoNamed,
  effect: async (wallets: Wallet[]) => {
    if (wallets.length === 0) return [];
    await walletModel.hideWallets(wallets);
    return wallets;
  },
});

const unhideAllFx = attach({
  source: $hiddenAutoNamed,
  effect: async (wallets: Wallet[]) => {
    if (wallets.length === 0) return [];
    await walletModel.restoreWallets(wallets);
    return wallets;
  },
});

export const hideUnnamedWalletsModel = {
  $mode,
  $visibleAutoNamed,
  $hiddenAutoNamed,
  hideAll: hideAllFx,
  unhideAll: unhideAllFx,
};
