name: Build and Deploy Storybook

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'src/**'

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: ⚙️ Install dependencies
        uses: ./.github/workflows/install-pnpm

      - name: Build 🔧
        run: |
          pnpm run build:storybook

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: storybook-static # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: storybook-static # The folder that we serve our Storybook files from
