name: Build and push Docker images

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'
      - 'stage-2-*' # Stage 2 tags used with date postfix, e.g. stage-2-20260401
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-dev-image:
    if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'dev' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy: &node_js_strategy
      fail-fast: false
      matrix:
        node-js-image-version: [24]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: ./.github/workflows/build-and-push-docker
        with:
          registry: ${{ env.REGISTRY }}
          image_name: ${{ env.IMAGE_NAME }}
          node_js_image_version: ${{ matrix.node-js-image-version }}
          image_label: latest
          build_type: development
          wallet_connect_project_id: ${{ secrets.WALLET_CONNECT_PROJECT_ID }}

  build-stage-2-image:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'stage-2-') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy: *node_js_strategy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: ./.github/workflows/build-and-push-docker
        with:
          registry: ${{ env.REGISTRY }}
          image_name: ${{ env.IMAGE_NAME }}
          node_js_image_version: ${{ matrix.node-js-image-version }}
          image_label: stage-2
          build_type: development
          wallet_connect_project_id: ${{ secrets.WALLET_CONNECT_PROJECT_ID }}
          set_version_from_tag_commit: 'true'

  build-release-and-pr-images:
    if: ${{ (github.event_name == 'push' && github.ref_type == 'tag' && !startsWith(github.ref_name, 'stage-2-')) || (github.event_name == 'pull_request' && contains(github.event.label.name, 'internal-build')) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy: *node_js_strategy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: ./.github/workflows/build-and-push-docker
        with:
          registry: ${{ env.REGISTRY }}
          image_name: ${{ env.IMAGE_NAME }}
          node_js_image_version: ${{ matrix.node-js-image-version }}
          image_label: ${{ github.event_name == 'pull_request' && 'stage' || github.ref_name }}
          build_type: production
          wallet_connect_project_id: ${{ secrets.WALLET_CONNECT_PROJECT_ID }}
