name: Check i18n keys

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  i18n:
    runs-on: ubuntu-latest

    steps:
      - name: ⚙️Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: ⚙️Install dependencies
        uses: ./.github/workflows/install-pnpm

      - name: 🔪 Check i18n
        run: pnpm run i18n:check:strict
