on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Env
        run: |
          # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
          env|sort

      - name: Set up secret file
        env:
          ACTIONS_CACHE_URL: ${{ secrets.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.ACTIONS_RUNTIME_TOKEN }}
        run: |
          echo $ACTIONS_CACHE_URL >> secrets.txt
          echo $ACTIONS_RUNTIME_TOKEN >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
