name: Lint code

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: ⚙️Checkout
        uses: actions/checkout@v4

      - name: ⚙️Install dependencies
        uses: ./.github/workflows/install-pnpm

      - name: 🔪 Check by typescript
        run: pnpm types

      - name: 🤞 Check by formatter
        run: pnpm fmt:check

      - name: 📝 Check by linter
        run: TIMING=1 pnpm lint

      - name: 🗺️ Check feature map
        run: pnpm check:feature-map
