name: Lint code

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: 🏃🏻‍♀️Checkout
        uses: actions/checkout@v4

      - name: 🥟 Use Bun
        uses: oven-sh/setup-bun@v2

      - name: 🔪 Check by typescript
        run: bun types

      - name: 🤞 Check by formatter
        run: bun fmt:check

      - name: 📝 Check by linter
        run: TIMING=1 bun lint
