name: Coverage report for pull request

on:
  # Temporary remove coverage tests for PRs
  # pull_request:
  #   paths:
  #     - 'src/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: ⚙️Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0
      - run: |
          git checkout -b dev origin/dev
          git checkout -

      - name: ⚙️Install dependencies
        uses: ./.github/workflows/install-pnpm

      - name: 🧪 Run tests with coverage
        run: pnpm test:coverage-new-files

      - name: Jest coverage comment
        id: coverage-report
        if: always()
        uses: MishaKav/jest-coverage-comment@642ef024cc554a34b7082cea12c7bf63575ae151 # v1.0.36
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          title: Current coverage report
          summary-title: Summary
          badge-title: Covered
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-title: Tests which was executed
          junitxml-path: ./junit.xml
          coverage-title: Coverage by files
          coverage-path: ./coverage.txt

