name: Run system tests - integration

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        type: string
        description: ALLURE_JOB_RUN_ID service parameter. Leave blank.
        required: false
      ALLURE_USERNAME:
        type: string
        description: ALLURE_USERNAME service parameter. Leave blank.
        required: false
  schedule:
    - cron: '0 6 * * *' # 9:00 GMT+3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max-old-space-size=8192"
  CI: true
  ALLURE_ENDPOINT: https://nova.testops.cloud/
  ALLURE_PROJECT_ID: 1
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: allure-results

jobs:
  system-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: ⚙️Checkout
        uses: actions/checkout@v4

      - name: ⚙️Install dependencies
        uses: ./.github/workflows/install-pnpm

      - name: ⚙️ Install test dependencies
        uses: ./.github/workflows/install-test

      - name: Run System Tests - Fee loading
        uses: ./.github/workflows/run-system-tests
        with:
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram_to: ${{ secrets.TELEGRAM_TO }}
          test_grep: '@fee-test'

