# update_internal_version.yaml
---
name: Update internal app version

on:
  pull_request:
    # types: [labeled]

env:
  CSC_FOR_PULL_REQUEST: true
  CI: true
  S3_BUCKET: s3://spektr-releases
  STORING_DAYS: 60

jobs:
  internal-version-increment:
    # if: ${{ github.event.label.name == 'internal-build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version from package.json
        id: pkg
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Update version from secret
        id: update_version
        run: |
          PKG_VERSION=${{ steps.pkg.outputs.version }}
          INTERNAL_BUILD_VERSION=${{ secrets.INTERNAL_BUILD_VERSION }}
          if [[ $PKG_VERSION == "$INTERNAL_BUILD_VERSION"* ]]; then
            # Increment the last number of INTERNAL_BUILD_VERSION
            NEW_VERSION=$(echo $INTERNAL_BUILD_VERSION | awk 'BEGIN{FS=OFS="-"} {n=split($NF, a, "."); if(n>1) $NF=a[1]"."a[2]+1; else $NF++;} 1')
          else
            NEW_VERSION="${PKG_VERSION}-1"
          fi
          echo "::set-output name=new_version::$NEW_VERSION"
        shell: bash

      - name: Write app version to secrets
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'INTERNAL_BUILD_VERSION'
          value: ${{ steps.update_version.outputs.new_version }}
          repository: novasamatech/nova-spektr
          token: ${{ secrets.WRITE_SECRET_PAT }}

      - name: Save PR number and head ref
        run: |
          echo "${{ github.event.pull_request.number }}" > pr.txt
          echo "${{ github.head_ref }}" > head_ref.txt

      - name: Upload PR number and head ref
        uses: actions/upload-artifact@v2
        with:
          name: github-context
          path: |
            pr.txt
            head_ref.txt
